### ISSUE TITLE
Passing arguments to function

### ISSUE THREAD

**Issue by axelbusch** [mikaelpatel/Arduino-Scheduler#26]
I try to adjust the SchedulerTaskCompletionQueue example. I would like to pass some arguments to the function that is executed by the worker. Such as:

void print(char c){
  Serial.println(c);
}
[..]
char c = 'a';
task_t task = print(c);
taskq.push(&task);

Unfortunately I can only pass functions without any parameters. Is that possible and how?

**Comment by mikaelpatel** [comment]
Nothing is impossible :) there are several approaches depending how high level syntax is wanted. The simplest is to add an environment pointer i.e. void* as a generic pointer to the task function.

**Comment by axelbusch** [comment]
Great idea! Thank you, that worked for me!

**Comment by mikaelpatel** [comment]
@axelbusch Great news! That is actually how it works in Cosa, one of my Arduino core projects; https://github.com/mikaelpatel/Cosa/blob/master/libraries/Nucleo/Thread.cpp#L72
