### ISSUE TITLE
Name in library.properties conflicts with Arduino Scheduler library.

### ISSUE THREAD

**Issue by sslupsky** [mikaelpatel/Arduino-Scheduler#29]
The name "Scheduler" in library.properties conflicts with the Arduino library of the same name.  This causes problems with the Library Manager and you cannot refresh the libraries and load this library.

I changed the name to "Arduino-Scheduler" and that fixes the problem.

**Comment by mikaelpatel** [comment]
Thanks for the heads up on this conflict. Updated to your suggestion. Guess this is still in conflict with the Arduino naming rules but will have to do for now. Cheers!
