### ISSUE TITLE
not an issue : just ported on XMOS

### ISSUE THREAD

**Issue by fabriceo** [mikaelpatel/Arduino-Scheduler#33]
Hi ,
I wanted to say a big thank you to Mikael for sharing this source code. The way the scheduler is implemented by using the standard set jump/lonjump and reserving stack space using a dynamic array local variable on the stack is very great.
I have ported the code with some changes for the XMOS cpu and a preliminary version and test code is described her : https://www.xcore.com/viewtopic.php?f=21&t=7272

Thanks again Mikael

**Comment by mikaelpatel** [comment]
Thanks for the update. Great news that you could port to XMOS. Please issue a pull request If you think your changes would be of interest for others. Cheers Mikael.
