### ISSUE TITLE
Cannot run a second task

### ISSUE THREAD

**Issue by Aucott** [mikaelpatel/Arduino-Scheduler#36]
This library seems ideal and has all the properties I require but I cannot seem to get a second task to run consistency.
Whatever task is declared first runs and then the "loop()" and then jumps back to the first task and only occasionally executes the second. I read the previous issue with the missing yields() in the loop() and tasks but this is not the case here.
It is very possible I am doing something wrong but at the moment cannot figure out what.

**Comment by mikaelpatel** [comment]
Please at least add the essential of your code together with platform version hardware and software.
